models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/ImagenesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class ImagenesController extends Controller {

    public function init(){
        parent::init();
        $this->layout="imagenes";
    }
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        /* crear un array de las fotos y las descripciones. */
        $imagenes = [
            [
                "nombre" => "1.jpg",
                "descripcion" => "Primera foto",
            ],
            [
                "nombre" => "2.jpg",
                "descripcion" => "Segunda foto",
            ],
            [
                "nombre" => "1.jpg",
                "descripcion" => "Primera foto",
            ],
            [
                "nombre" => "2.jpg",
                "descripcion" => "Segunda foto",
            ],
            [
                "nombre" => "1.jpg",
                "descripcion" => "Primera foto",
            ],
            [
                "nombre" => "2.jpg",
                "descripcion" => "Segunda foto",
            ],
            [
                "nombre" => "1.jpg",
                "descripcion" => "Primera foto",
            ],
            [
                "nombre" => "2.jpg",
                "descripcion" => "Segunda foto",
            ],
            [
                "nombre" => "1.jpg",
                "descripcion" => "Primera foto",
            ],
            [
                "nombre" => "2.jpg",
                "descripcion" => "Segunda foto",
            ],
            [
                "nombre" => "1.jpg",
                "descripcion" => "Primera foto",
            ],
            [
                "nombre" => "2.jpg",
                "descripcion" => "Segunda foto",
            ]
        ];
        
        

        return $this->render('listar', [
                    "imagenes" => $imagenes,
                    "titulo"=>"Las imagenes del proyecto",
                    "bloque2"=>"Estas son las imagenes del proyecto que son pasadas desde el controlador."
        ]);
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;

use yii\web\Controller;


class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionNumeros()
    {
        //creo un array con numeros 
        $numeros=[1,2,3,4,34,23,12];
        return $this->render('listar',[
            "datos"=>$numeros
        ]);
    }

    public function actionLetras()
    {
        $letras=["a","c","h","j"];
        return $this->render('listar',[
            "datos"=>$letras
        ]);
    }
    
}

views/imagenes/listar.php
<?php

use app\widgets\Miniaturas;

/* cargamos el primer bloque */
$this->beginBlock("Titulo");
echo $titulo;
$this->endBlock("Titulo");
/* fin del primer bloque */

/* cargamos el segundo bloque */
$this->beginBlock("Bloque2");
echo $bloque2;
$this->endBlock("Bloque2");
/* fin del segundo bloque */

echo Miniaturas::widget([
    "imagenes" => $imagenes
]);

views/layouts/imagenes.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => Yii::$app->name,
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Listar Numeros', 'url' => ['/site/numeros']],
                    ['label' => 'Listar Letras', 'url' => ['/site/letras']],
                    ['label' => 'Imagenes', 'url' => ['/imagenes']],
                ],
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>

                <h1>
                    <?php
                    if (isset($this->blocks['Titulo'])) {
                        echo $this->blocks['Titulo'];
                    } else {
                        echo "Ejemplo de Titulo";
                    }
                    ?>
                </h1>

                <?= $content ?>
                <div class="well wel-lg">
                    <?php
                    if (isset($this->blocks['Bloque2'])) {
                        echo $this->blocks['Bloque2'];
                    } else {
                        echo "Ejemplo de Bloque2";
                    }
                    ?>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; Ramon Abramo <?= date('Y') ?></p>

                <p class="pull-right"><?= Yii::powered() ?></p>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Listar Numeros', 'url' => ['/site/numeros']],
            ['label' => 'Listar Letras', 'url' => ['/site/letras']],
            ['label' => 'Imagenes', 'url' => ['/imagenes']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Ramon Abramo <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/_elemento.php
<?=
yii\helpers\Html::tag("li", "indice=$i, valor=$v", [
    "class" => "list-group-item"
]) //vamos a utilizar helpers para crear la etiqueta
?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/listar.php
<ul class="list-group">
    <?php
    foreach($datos as $indice=>$valor){
        echo $this->render("_elemento",[
            "i"=>$indice,
            "v"=>$valor,
    ]);
    }
    ?>
</ul>